services:
  libreoffice:
    build:
      context: .
    image: devforge/libreoffice-local:latest
    container_name: libreoffice-start-dev
    working_dir: /data
    volumes:
      - ./data:/data
      - ./fonts:/usr/local/share/fonts/custom:ro
    environment:
      TZ: Asia/Shanghai
      HOME: /tmp/libreoffice-home
    deploy:
      resources:
        limits:
          memory: 2048M
        reservations:
          memory: 512M
